// angular-frontend/src/app/website/website.component.ts
import { Component } from '@angular/core';
import { RouterLink, RouterLinkActive, RouterOutlet } from '@angular/router';

@Component({
  selector: 'app-website',
  standalone: true,
  imports: [RouterOutlet, RouterLink, RouterLinkActive],
  templateUrl: './website.component.html',
})
export class WebsiteComponent {

}

<div class="w-full min-h-[calc(100vh_-_60px)] flex flex-col justify-center items-center gap-8">
  <h1 class="text-3xl font-bold">
    <span class="font-bold text-red-600">
      Angular
    </span>
    "to-do"
    notes app
  </h1>

  <div class="flex justify-center items-center gap-2 text-xl">
    <a class="px-4 py-2 bg-red-600 rounded-md text-white font-bold" routerLink="/sign-in"
      routerLinkActive="active">Sign-In</a>
    <a class="px-4 py-2 font-bold" routerLink="/sign-up" routerLinkActive="active">Sign-Up</a>
  </div>
</div>

// vue-frontend/src/components/modules/website.vue
<template>
  <div class="w-full min-h-[calc(100vh_-_60px)] flex flex-col justify-center items-center gap-8">
    <h1 class="text-3xl font-bold">
      <span class="font-bold text-green-600">
        Vue
      </span>
      "to-do"
      notes app
    </h1>

    <div class="flex justify-center items-center gap-2 text-xl">
      <a class="px-4 py-2 bg-green-600 rounded-md text-white font-bold" href="/sign-in">Sign-In</a>
      <a class="px-4 py-2 font-bold" href="/sign-up">Sign-Up</a>
    </div>
  </div>
</template>
